### ISSUE TITLE
boost::multiprecision::int128_t gives unexpected results when exporting and importing bits

### ISSUE THREAD

**Issue by cpcloud** [boostorg/multiprecision#21] opened 2017-04-09 18:09 UTC
When using `export_bits` with the number `2 ^ 127 - 1`, I cannot roundtrip convert between `int128_t` values and bytes generated by `export_bits` on that value.

```cpp
// largest positive number representable by two's complement 128-bit integer
int128_t value("170141183460469231731687303715884105727");
uint8_t stack_bytes[16] = {0};
uint8_t* bytes = stack_bytes;
export_bits(value, bytes, 8, false); // chunks of 8 bits, LSB first
```

If I then immediately do:

```cpp
int128_t imported_value;
import_bits(imported_value, bytes, bytes + 16, 8, false);
```

The number I get back is `2 ^ 128 - 1`, with every bit in each underlying byte set to 1. I understand that boost is *not* using two's complement, but sign-magnitude.

In either case, I would expect that `2 ^ 127 - 1` is represented by 127 bits set to 1 and the 128th bit set to 0 instead of all 128 bits set to 1.

Am I misunderstanding something about the representation, or is this expected behavior?

More generally, Is there a documented/sanctioned way to recreate an `int128_t` number from its underlying bits? I'm fine with handling the sign bit on my own.

**Comment by jzmaddock** [comment] 2017-04-10 11:41
On 09/04/2017 19:09, Phillip Cloud wrote:
>
> When using |export_bits| with the number |2 ^ 127 - 1|, I cannot 
> roundtrip convert between |int128_t| values and bytes generated by 
> |export_bits| on that value.
>
> // largest positive number representable by two's complement 128-bit 
> integer
> int128_t  value("170141183460469231731687303715884105727");
> uint8_t  stack_bytes[16] = {0};
> uint8_t* bytes = stack_bytes;
> export_bits(value, bytes,8,false);// chunks of 8 bits, LSB first
>
> If I then immediately do:
>
> int128_t  imported_value;
> import_bits(imported_value, bytes, bytes +16,8,false);
>
> The number I get back is |2 ^ 128 - 1|, with every bit in each 
> underlying byte set to 1. I understand that boost is /not/ using two's 
> complement, but sign-magnitude.
>
> In either case, I would expect that |2 ^ 127 - 1| is represented by 
> 127 bits set to 1 and the 128th bit set to 0 instead of all 128 bits 
> set to 1.
>
> Am I misunderstanding something about the representation, or is this 
> expected behavior?
>

No it's a bug, if you're using GCC or clang, then it's this bug: 
https://svn.boost.org/trac/boost/ticket/12627 and will be fixed in the 
next release (currently in beta).

> More generally, Is there a documented/sanctioned way to recreate an 
> |int128_t| number from its underlying bits? I'm fine with handling the 
> sign bit on my own.
>

I'm afraid this is it, the bug is actually in the export, not the import.

The next release will also support direct conversion to and from __int128.

Otherwise you're stuck shifting out blocks of N-bits at a a time.

---
This email has been checked for viruses by AVG.
http://www.avg.com

**Comment by cpcloud** [comment] 2017-04-14 17:58
@jzmaddock Is there a regression test for this?

**Comment by jzmaddock** [comment] 2017-05-31 18:32
Added test case in this commit: https://github.com/boostorg/multiprecision/commit/10efe3d1691ec8a94ad2ac592ae6e47cc358d236

**Closed by jzmaddock** 2017-05-31 18:32 UTC

**Comment by mariospr** [comment] 2022-02-24 12:29
I'm sorry to bring this old issue back to life, but I was trying to use Booth multiprecision library to work with 256-bit integers, signed and unsigned, and I'm bit confusing by the fact that `std::numeric_limits<T>::{min,max}()` are not returning the values that I'd expect.

Instead they seem to be returning exactly the same magnitude for max values both for signed and unsigned, and then simply a negative version of `std::numeric_limits<boost::multiprecision::uint256_t>::max()` when I ask for `std::numeric_limits<boost::multiprecision::int256_t>::min()`.

In an attempt to better explain what I'm seeing VS what I'd expect, I wrote this small program which I built with a standalone version of the Boost Multiprecision Library ([using this PR](https://github.com/boostorg/multiprecision/pull/418)):
```c++
#include <boost/multiprecision/cpp_int.hpp>
#include <iostream>
#include <limits>

int main() {
    // Expected:
    //   Decimal: 0
    //   Hex: 0x0000000000000000000000000000000000000000000000000000000000000000
    std::cout << "std::numeric_limits<boost::multiprecision::uint256_t>::min(): "
        << std::numeric_limits<boost::multiprecision::uint256_t>::min()
        << std::endl;
    // Actual output (OK): 0

    // Expected:
    //   Decimal: 115792089237316195423570985008687907853269984665640564039457584007913129639935
    //   Hex: 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    std::cout << "std::numeric_limits<boost::multiprecision::uint256_t>::max(): "
        << std::numeric_limits<boost::multiprecision::uint256_t>::max()
        << std::endl;  
    // Actual output (OK): 115792089237316195423570985008687907853269984665640564039457584007913129639935

    // Expected:
    //   Decimal: -57896044618658097711785492504343953926634992332820282019728792003956564819968
    //   Hex: 0x8000000000000000000000000000000000000000000000000000000000000000
    std::cout << "std::numeric_limits<boost::multiprecision::int256_t>::min(): "
        << std::numeric_limits<boost::multiprecision::int256_t>::min()
        << std::endl;  
    // Actual output (FAIL): -115792089237316195423570985008687907853269984665640564039457584007913129639935

    // Expected:
    //   Decimal: 57896044618658097711785492504343953926634992332820282019728792003956564819967
    //   Hex: 0x0x7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    std::cout << "std::numeric_limits<boost::multiprecision::int256_t>::max(): "
        << std::numeric_limits<boost::multiprecision::int256_t>::max()
        << std::endl;  
    // Actual output (FAIL): 115792089237316195423570985008687907853269984665640564039457584007913129639935
}
```
...and **this is the output it produces**:
```
std::numeric_limits<boost::multiprecision::uint256_t>::min(): 0
std::numeric_limits<boost::multiprecision::uint256_t>::max(): 115792089237316195423570985008687907853269984665640564039457584007913129639935

std::numeric_limits<boost::multiprecision::int256_t>::min(): -115792089237316195423570985008687907853269984665640564039457584007913129639935
std::numeric_limits<boost::multiprecision::int256_t>::max(): 115792089237316195423570985008687907853269984665640564039457584007913129639935
```

To me this is very confusing, but it's certainly possible this is not really an issue and me misunderstanding how to work with these numbers, so I'm not opening a new issue for now and commenting here just in case it's (even remotely) related to this issue. Either way, any comment or hint is welcome, even if it's just to tell me I'm doing something obviously wrong.

Thanks in advance!

PS: FWIW, I observer equivalent behaviour with `boost::multiprecision::int128_t`.

**Comment by jzmaddock** [comment] 2022-02-24 12:36
This is expected, all cpp_int's are sign-magnitude representation, not 2's complement, so the maximum value in a uint256_t and an int256_t are the same and are 2^256 - 1.

So.... you're doing nothing wrong, but this is intended behaviour, and these types are NOT bit-compatible with 2's complement built in integers.  For 99% of use cases this makes no difference, it's only when you start doing bit-fiddling on signed numbers (which is undefined behaviour anyway) that you see the difference.

**Comment by mariospr** [comment] 2022-02-24 13:18
Thanks a lot for the quick response!

> This is expected, all cpp_int's are sign-magnitude representation, not 2's complement, so the maximum value in a uint256_t and an int256_t are the same and are 2^256 - 1.

Hmmm... I guess this is what is confusing to me: if using sign-magnitude my expectation would be that, with 256 bits, you could represent numbers from `-[2(n-1) -1]` to `+[2(n-1) -1]`, that is, so the maximum value would be 2^255 - 1 instead. That's the part that puzzles me the most, how you can get up to 2^256 - 1 (and down to -(2^256 - 1)) using sign-magnitude and 256 bits.

Also, if one bit is used for the sign then I also don't understand how you can get the same maximum both for int256 and uint256, which should have 1 bit more available for the magnitude part. In my mind, uint256_t should get up to 2^256 - 1 indeed, but not int256_t (max should be 2^255 - 1, no?).

> So.... you're doing nothing wrong, but this is intended behaviour, and these types are NOT bit-compatible with 2's complement built in integers. For 99% of use cases this makes no difference, it's only when you start doing bit-fiddling on signed numbers (which is undefined behaviour anyway) that you see the difference.

Yes, I understand the binary representation is different but, as I said above, I'm still confused by the maximum and minimum value you can get for signed integers with just 256 bits. If you could you clarify this a bit more, that would be great.

Thanks again
